<table>
<table border = 5  align = center bgcolor="white" cellspacing="10px">

<tr>
<td> <a href="https://drive.google.com/file/d/14sEPNG7RArYv9ZwSK0QNyxUgrihlbrn2/view?usp=sharing"> <img alt="Colaboratory logo" width="150px"  src="https://miro.medium.com/max/986/1*S2AyJcdw8EPcn7gwDVSBCA.png" align="left" hspace="10px" vspace="0px" /> </a>   </td>
   
<td></td>
    
<td><a href="https://mybinder.org/v2/git/https%3A%2F%2Fgitmilab.redclara.net%2FhalleyUIS%2Fmoncora.git/0936d792b8e87847f8624bb906f74cd24badf030?urlpath=lab%2Ftree%2FBook%2FJupyter_Notebooks%2FFunciones_Librerias.ipynb"><img src="https://mybinder.org/static/images/logo_social.png" alt="Alternative text" width="150px"  /></a>
</td>

</tr>

</table>
    
<br>

# <strong>Funciones y librerías</strong>



## Programando sin barreras III


<blockquote>
No te pierdas el vídeo de <a href="https://www.youtube.com/watch?v=inN8seMm7UI">Funciones y librerías</a>. 
</blockquote>



---

## <strong>Funciones</strong>

Una función en programación nos permite definir un bloque de código que deseamos usar varias veces en nuestro programa, es decir nos ayuda a reducir la redundancia en nuestro programa,  eeduciendo el número de líneas de código. 


<strong>Sintaxis</strong>

En Python para poder crear nuestras propias funciones es necesario seguir una estructura especifica, la cual separo en los siguientes tips:

1.   Primero la palabra reservada ```def```
2.   Seguido del nombre de la función
3.   Paréntesis"()", si tu función recibirá alguna variable irá dentro de estos paréntesis si no va vacío.
4.   Agregamos dos puntos ":"
5.   Después de esto ponemos las líneas de código que queremos que ejecute nuestra función.
6.   Usamos la palabra reservada ```return``` si queremos que nuestra función devuelva algún valor.

<div class="alert alert-block alert-info">
<b>Nota:</b> El  nombre que se les asigne a las funciones para crear su definición tiene que ser en minúsculas y las palabras se separan con guión bajo.
</div>


<strong>Ejemplo</strong>

El nombre de la función es suma y recibe dos parámetros y devuelve una variable c
```
def suma(a,b):
  c=a+b
  return c
```

Solo quedaría llamar la función!, veamoslo en el siguiente código.


*

**Nota:**
La estructura de una función es la siguiente:

```
    def funcion(a,b):
        c = a*b
        return c
```

* `def` es la palabra reservada para crear funciones en python. Ella le dice a Python que a continuación se define una función.
* `funcion` es el nombre de la función
* `funcion(a,b): c = a*b` significa que la función `función` toma dos variables `a, b` y las multiplica entre sí.
* `c= a*b` constituye el cuerpo de la función.
* `return c` significa que la función devuelve el valor c. Indica el final de la función, después de ejecutado el `return` la ejecución de la función termina.

Veámos:

In [3]:
def funcion(a,b):
    c = a*b
    return c

Vemos que la anterior celda no hace nada. En efecto, ella solo define la función pero no la ejecuta. Una vez definida, la podemos usar cuántas veces queramos más adelante:

In [5]:
funcion(4,5)

20

In [7]:
funcion(4,7), funcion(4,8), funcion(4,10)

(28, 32, 40)

/

In [6]:
# Se crea una función que calcule la suma de dos números
def suma(a,b):
  c=a+b
  return c

#Se llama la función indicando los parámetros
suma(10,4)


14

In [7]:
# Si llamamos la función con nuevos parámetros, tendremos un nuevo resultado:
suma(30,56)

86

In [4]:
# Se crea la misma función pero en vez de retornar un valor le pedimos que lo 
# imprima
def suma(a,b):
  c=a+b
  print("La suma es: ",c)

#Se llama la función indicando los parámetros
suma(10,4)


La suma es:  14


*

Dentro de una función podemos hacer los códigos que deseemos, incluyendo ciclos, print, o otras funciones

In [8]:
def suma(a,b):
  c = a+b
  print("a + b =",c)

In [9]:
suma(10,20)

a + b = 30


In [10]:
def factorial(n):
    c = 1
    for i in range(1,n+1):
        c = c*i
    return c

In [20]:
factorial(10)

3628800

/

Un momento!,```print()``` ¿No se te hace muy familiar?, CLARO!. 
```print()``` También es una función, en python existen un grán número de funciones. En este notebook veremos unas cuantas...



*   ```print()``` Muestra texto en pantalla
*   ```len()```   Nos muestra la longitud del parámetro que ingresemos
*   ```max()```   En un arreglo de números indica cual es el mayor
*   ```min()```   En un arreglo de números indica cual es el menor


Te reto a buscar más funciones y aplicarlas en tu código.


In [ ]:
# Len() muestra el tamaño del parámetro que ingresemos. En este caso mostró el
# tamaño de la cadena de texto
len("La mujer cantaba mientras programaba")

10

In [ ]:
# Max() devuelve el valor mayor entre varios
max([3,4,8,10])

10

In [ ]:
#Intentalo con el min() en esta celda


Podemos crear diferentes funciones. Por ejemplo, creemos una función que multiplique dos números:


In [8]:
def Mult(a, b):
    c = a * b
    return(c)

In [10]:
# Podemos multiplicar dos enteros
Mult(2, 3)


6

In [11]:
# Podemos multiplicar dos numeros float
Mult(1.6, 3.6)


5.760000000000001

In [14]:
# Podemos multiplicar dos variables de diferente tipo
Mult(2, "Hola")

'HolaHola'

*

**Nota:** Existen algunas funciones predefinidas en python que vale la pena analizar.

In [21]:
x = [1, 2, 3, 4, 5, 6, 7, 8]

max(x) #Valor máximo de una lista

8

In [22]:
min(x) #Valor mínimo de una lista

1

In [24]:
len(x) #Cantidad de elementos de una lista

8

In [25]:
print('Hola mundo')

Hola mundo


Las funciones predefinidas `max`, `min` y `len` se dice que tienen nombres reservados por el sistema, lo que significa que no podemos usarlas para definir variables.

/

<div class="alert alert-block alert-info">
<b>Nota:</b>
     Una variable que es declarada dentro de una función se llama <strong>variable local</strong>. Esta variable solo existe dentro de la función.
     Una variable que es declarada fuera de una función se llama  <strong>variable global</strong>, y su valor es accesible y modificable a lo largo del programa. 
    
</div>



In [2]:
# Definición de función:

def square(a):
    
    # b y c son variables locales
    b = 1
    c = a * a + b
    print( "(a+1)*(a+1)=", c) 
    return(c)

# x y y son variables globales

x = 3
y = square(x)
y



(a+1)*(a+1)= 10
Yo recibí 1
Ahora tengo 2
1


In [3]:
#Mira otro ejemplo:
def my_function1(var):
    print("Yo recibí", var)
    var += 1
    print("Ahora tengo", var)


var = 1
my_function1(var)
print(var)

Yo recibí 1
Ahora tengo 2
1


In [1]:
#Puedes definir variables globales  dentro de funciones de la siguiente manera
def my_function():
    global var
    var = 2
    print("¿Conozco a aquella variable?", var)


var = 1
my_function()
print(var)


¿Conozco a aquella variable? 2
2


*

Dentro de una función siempre es posible definir variables que hacen parte del cuerpo de la función. Estas variables se denominan *variables locales*.

En oposición, toda variable definida afuera de una función se le denomina *variable global*. Ellas pueden cambiarse por fuera de una función.

Las variables locales solo pueden ser modificadas adentro de la función y no interfieren con nada que esté afuera, aunque tenga su mismo nombre:

In [33]:
def suma(a,b):
    c = a+b
    print('Variables locales \n')
    print('a =',a)
    print('b =',b)
    return c    

a = 5
b = 5
suma(10,2)

print('Variables globales \n')
print('a =',a)
print('b =',b)


Variables locales 

a = 10
b = 2
Variables globales 

a = 5
b = 5


En el ejemplo anterior vemos que las variables `a` y `b` definidas en `suma(a,b)` no se ven afectadas por las variables del mismo nombre afuera de la función.

/

<img width="150px"  src="https://raw.githubusercontent.com/AndresGuarin/Images/main/moncora_ejercicios_cartel.png" align="center">

---

**1.** Define una función que reciba como argumento un número y retone el factorial de dicho número 
>El factorial (!) de un número entero positivo es el producto de todos los números de 1 hasta el número: por ejemplo 3! == 3 × 2 × 1. 



**2.** Cree una función que encuentre el elemento más pequeño de una lista dada.



**3.** Escribe una función que de la tabla de multiplicar de un número dado

**4.** Realiza un programa donde el usuario ingrese un número y el programa le diga si es primo dicho número o no.
>**Teorema de Wilson**:
> puede afirmarse que un número n> 1 es primo si y solo si (n− 1)! ≡ − 1 (mod n)

Nota: 
26≡11 (mod 5)
significa que 
- 26 mod 5=1 
- 11 mod 5=1 

In [37]:
-1%20

19

---

## <strong> La magia de las Librerías</strong>

Las librerías en python son una herramienta fundamental a la hora de programar ya que nos permiten ampliar nuestras funcionalidades apartir de módulos ya creados.

<div class="alert alert-block alert-success">
Los modulos son paquetes de codigo (paquetes de funciones) escrito por personas externas que estan contenidos en el lenguaje de pyhton, pudieron ser los desarrolladores de llenguaje pyhton u otras, que nosotros tenemos a disposicion para ejecutar o usar que haces el trabajo por nosotros.
</div>



La forma de llamar una librería comienza con la palabra reservada ```import``` esta palabra seguida del nombre de la librería que queremos usar traerá todas las funcionalidades la librería. En python existen un sin número de librerías en este repaso nos centraremos en tres <strong>math</strong>,<strong>numpy</strong> y <strong>matplotlib</strong>

Para poder usar la librería en las siguientes celdas de nuestro notebook debemos hacer uso del nombre seguido del punto y la función que se va usar.




In [ ]:
# Aqui importamos una librería
import math

In [ ]:
# Se hace uso de la librería math y la función pow() que nos permite elevar el 
# primer número a la cantidad del segundo número
math.pow(2,4)

16.0

<blockquote>
Para hacernos una idea de lo últil que son las librerías en el siguiente link podrán visitar todas las librerías de <a href="https://docs.python.org/es/3/library/math.html"><strong>math</strong></a>. No es necesario usarlas todas, solamente ir haciendo uso de las que nuestro programa necesite.
</blockquote>


Mira este juego de "piedra, papel o tijera" usando la librería random:

**Comenta cada línea con su función en el código:**

In [1]:
import random

print("¡Juguemos Piedra, Papel o Tijera!")
print("1. Piedra \n2. Papel \n3. Tijera")

opciones = ["Piedra", "Papel", "Tijera"]
opcion_jugador = int(input("Escribe el número de tu opción: "))
opcion_computadora = random.randint(1, 3)

print("\n")
print("Tú elegiste", opciones[opcion_jugador-1])
print("Python eligió", opciones[opcion_computadora-1])
print("\n")

if opcion_jugador == opcion_computadora:
    print("¡Empate!")
elif opcion_jugador == 1 and opcion_computadora == 3 or opcion_jugador == 2 and opcion_computadora == 1 or opcion_jugador == 3 and opcion_computadora == 2:
    print("¡Ganaste!")
else:
    print("Python te ganó :(")

¡Juguemos Piedra, Papel o Tijera!
1. Piedra 
2. Papel 
3. Tijera
Escribe el número de tu opción: 2


Tú elegiste Papel
Python eligió Piedra


¡Ganaste!


Vamos ahora ver una librería fundamental para el cálculo de matrices y análisis de datos. La famosisima ```numpy```

In [1]:
import numpy

In [2]:
# Crearemos un vector o array de una dimensión
a1 = numpy.array([1,2,3,4])
print(type(a1))
print(a1)

<class 'numpy.ndarray'>
[1 2 3 4]


A la hora de llamar una librería tener que repetir su nombre cada vez que la vamos a usar. Esto se vuelve tediozo y más con algunas que su nombre son super largos! Pero, podemos haver uso de la palabra reservada ```as``` la cual nos permitirá poner un alias a nuestra librería y poder hacer uso de esta por medio de ese alías.

In [3]:
# Llamamos la librería numpy pero le asignamos el alías np
import numpy as np

In [4]:
# Crearemos un vector o array de una dimensión
b1 = np.array([5,6,7,8])
print(type(b1))
print(b1)

<class 'numpy.ndarray'>
[5 6 7 8]


<div class="alert alert-block alert-danger">

El alías lo podemos poner a nuestro gusto, pero en programación existe un estandár a la hora de poner estos alías y hacen que nuestro código sea más fácil de leer por otra persona.
</div>




In [ ]:
# Llamamos la librería numpy pero le asignamos el alís pppdnombreinventado
import numpy as pppdnombreinventado

In [ ]:
# Crearemos un vector o array de una dimensión
c1 = pppdnombreinventado.array([8,9,10,11])
print(type(c1))
print(c1)

<class 'numpy.ndarray'>
[ 8  9 10 11]


### Conociendo un poco más de ```numpy```

Existen varios atributos y funciones que describen las características de un array.

- a.ndim : Devuelve el número de dimensiones del array a.
- a.shape : Devuelve una tupla con las dimensiones del array a.
- a.size : Devuelve el número de elementos del array a.
- a.dtype: Devuelve el tipo de datos de los elementos del array a.


In [2]:
import numpy as np

a = np.array([1, 2, 3])   # crea una array de un rango
print("El tipo de la variable a es:", type(a))            
print(("y su tamaño es:", a.shape)            



<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
#Puedes imprimir cada uno de los elementos de a
print(a[0], a[1], a[2])   


In [ ]:
#o cambiarlos
a[0] = 5                  # cambia un elemento de la array
print(a)                  


In [8]:
#Podemos aumentar el rango de la array
b = np.array([[1,2,3],[4,5,6]])    # crea una array de segundo rango
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   #imprimir cada uno de sus elementos

(2, 3)
1 2 4


```numpy``` también tiene muchas funciones para crear arrays

In [9]:
a = np.zeros((2,2))   # crea una array de ceros
print("Array de ceros:\n",a, "\n")              

b = np.ones((1,2))    # crea una array de unos
print("Array de unos:\n",b)              

c = np.full((2,2), 7)  # crea una array con numeros constantes
print("Array de con constantes:\n",c, "\n")               
    

e = np.random.random((2,2))  # crea una array con valores aleatorios
print("Array aleatoria:\n",e, "\n")  

Array de ceros:
 [[0. 0.]
 [0. 0.]] 

Array de unos:
 [[1. 1.]]
Array de con constantes:
 [[7 7]
 [7 7]] 

Array aleatoria:
 [[0.64373792 0.25629592]
 [0.73398727 0.23813141]] 



<img width="150px"  src="https://raw.githubusercontent.com/AndresGuarin/Images/main/moncora_ejercicios_cartel.png" align="center">

---

**1.** ¿Cual es el resultado de las siguientes expresiones?
- 0 * np.nan
- np.nan == np.nan
- np.inf > np.nan
- np.nan - np.nan
- np.nan in set([np.nan])
- 0.3 == 3 * 0.1





**2.** Reemplace todos los números impares por -1 en esta array: 

``` 
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
